[project]
authors = [
    { name = "Maya Cranor", email = "maya@cyvl.ai" },
]
description = "Utility functions for round generation"
name = "models"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

dependencies = [
    "pydantic>=2.10.6",
    "pydantic-settings>=2.9.1",
]

[tool.uv.sources]
state-management = { workspace = true }

[build-system]
build-backend = "uv_build"
requires      = ["uv_build>=0.8.3,<0.9.0"]